<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1beta1/common/common.proto

namespace GPBMetadata\Google\Devtools\Containeranalysis\V1Beta1\Common;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4030a3d676f6f676c652f646576746f6f6c732f636f6e7461696e6572" .
            "616e616c797369732f763162657461312f636f6d6d6f6e2f636f6d6d6f6e" .
            "2e70726f746f120f677261666561732e7631626574613122280a0a52656c" .
            "6174656455726c120b0a0375726c180120012809120d0a056c6162656c18" .
            "022001280922350a095369676e617475726512110a097369676e61747572" .
            "6518012001280c12150a0d7075626c69635f6b65795f6964180220012809" .
            "2a8b010a084e6f74654b696e6412190a154e4f54455f4b494e445f554e53" .
            "5045434946494544100012110a0d56554c4e45524142494c495459100112" .
            "090a054255494c44100212090a05494d4147451003120b0a075041434b41" .
            "47451004120e0a0a4445504c4f594d454e541005120d0a09444953434f56" .
            "4552591006120f0a0b4154544553544154494f4e1007427b0a19696f2e67" .
            "7261666561732e763162657461312e636f6d6d6f6e50015a56676f6f676c" .
            "652e676f6c616e672e6f72672f67656e70726f746f2f676f6f676c656170" .
            "69732f646576746f6f6c732f636f6e7461696e6572616e616c797369732f" .
            "763162657461312f636f6d6d6f6e3b636f6d6d6f6ea20203475241620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

