<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1beta1/provenance/provenance.proto

namespace Grafeas\V1beta1\Provenance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container message for hash values.
 *
 * Generated from protobuf message <code>grafeas.v1beta1.provenance.Hash</code>
 */
class Hash extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The type of hash that was performed.
     *
     * Generated from protobuf field <code>.grafeas.v1beta1.provenance.Hash.HashType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Required. The hash value.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           Required. The type of hash that was performed.
     *     @type string $value
     *           Required. The hash value.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Containeranalysis\V1Beta1\Provenance\Provenance::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The type of hash that was performed.
     *
     * Generated from protobuf field <code>.grafeas.v1beta1.provenance.Hash.HashType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Required. The type of hash that was performed.
     *
     * Generated from protobuf field <code>.grafeas.v1beta1.provenance.Hash.HashType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Grafeas\V1beta1\Provenance\Hash_HashType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Required. The hash value.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Required. The hash value.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

}

