<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/securitycenter/v1beta1/run_asset_discovery_response.proto

namespace GPBMetadata\Google\Cloud\Securitycenter\V1Beta1;

class RunAssetDiscoveryResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a82040a46676f6f676c652f636c6f75642f736563757269747963656e74" .
            "65722f763162657461312f72756e5f61737365745f646973636f76657279" .
            "5f726573706f6e73652e70726f746f1223676f6f676c652e636c6f75642e" .
            "736563757269747963656e7465722e763162657461311a1c676f6f676c65" .
            "2f6170692f616e6e6f746174696f6e732e70726f746f22ec010a1952756e" .
            "4173736574446973636f76657279526573706f6e736512530a0573746174" .
            "6518012001280e32442e676f6f676c652e636c6f75642e73656375726974" .
            "7963656e7465722e763162657461312e52756e4173736574446973636f76" .
            "657279526573706f6e73652e5374617465122b0a086475726174696f6e18" .
            "022001280b32192e676f6f676c652e70726f746f6275662e447572617469" .
            "6f6e224d0a05537461746512150a1153544154455f554e53504543494649" .
            "45441000120d0a09434f4d504c455445441001120e0a0a53555045525345" .
            "4445441002120e0a0a5445524d494e415445441003427e0a27636f6d2e67" .
            "6f6f676c652e636c6f75642e736563757269747963656e7465722e763162" .
            "6574613150015a51676f6f676c652e676f6c616e672e6f72672f67656e70" .
            "726f746f2f676f6f676c65617069732f636c6f75642f7365637572697479" .
            "63656e7465722f763162657461313b736563757269747963656e74657262" .
            "0670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

