<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/securitycenter/v1beta1/source.proto

namespace GPBMetadata\Google\Cloud\Securitycenter\V1Beta1;

class Source
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2020a30676f6f676c652f636c6f75642f736563757269747963656e74" .
            "65722f763162657461312f736f757263652e70726f746f1223676f6f676c" .
            "652e636c6f75642e736563757269747963656e7465722e76316265746131" .
            "22410a06536f75726365120c0a046e616d6518012001280912140a0c6469" .
            "73706c61795f6e616d6518022001280912130a0b6465736372697074696f" .
            "6e180320012809427e0a27636f6d2e676f6f676c652e636c6f75642e7365" .
            "63757269747963656e7465722e7631626574613150015a51676f6f676c65" .
            "2e676f6c616e672e6f72672f67656e70726f746f2f676f6f676c65617069" .
            "732f636c6f75642f736563757269747963656e7465722f76316265746131" .
            "3b736563757269747963656e746572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

