# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1beta1/image/image.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grafeas.v1beta1.image.Layer" do
    optional :directive, :enum, 1, "grafeas.v1beta1.image.Layer.Directive"
    optional :arguments, :string, 2
  end
  add_enum "grafeas.v1beta1.image.Layer.Directive" do
    value :DIRECTIVE_UNSPECIFIED, 0
    value :MAINTAINER, 1
    value :RUN, 2
    value :CMD, 3
    value :LABEL, 4
    value :EXPOSE, 5
    value :ENV, 6
    value :ADD, 7
    value :COPY, 8
    value :ENTRYPOINT, 9
    value :VOLUME, 10
    value :USER, 11
    value :WORKDIR, 12
    value :ARG, 13
    value :ONBUILD, 14
    value :STOPSIGNAL, 15
    value :HEALTHCHECK, 16
    value :SHELL, 17
  end
  add_message "grafeas.v1beta1.image.Fingerprint" do
    optional :v1_name, :string, 1
    repeated :v2_blob, :string, 2
    optional :v2_name, :string, 3
  end
  add_message "grafeas.v1beta1.image.Basis" do
    optional :resource_url, :string, 1
    optional :fingerprint, :message, 2, "grafeas.v1beta1.image.Fingerprint"
  end
  add_message "grafeas.v1beta1.image.Details" do
    optional :derived_image, :message, 1, "grafeas.v1beta1.image.Derived"
  end
  add_message "grafeas.v1beta1.image.Derived" do
    optional :fingerprint, :message, 1, "grafeas.v1beta1.image.Fingerprint"
    optional :distance, :int32, 2
    repeated :layer_info, :message, 3, "grafeas.v1beta1.image.Layer"
    optional :base_resource_url, :string, 4
  end
end

module Grafeas
  module V1beta1
    module Image
      Layer = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.image.Layer").msgclass
      Layer::Directive = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.image.Layer.Directive").enummodule
      Fingerprint = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.image.Fingerprint").msgclass
      Basis = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.image.Basis").msgclass
      Details = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.image.Details").msgclass
      Derived = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.image.Derived").msgclass
    end
  end
end
