# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1beta1/package/package.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grafeas.v1beta1.package.Distribution" do
    optional :cpe_uri, :string, 1
    optional :architecture, :enum, 2, "grafeas.v1beta1.package.Architecture"
    optional :latest_version, :message, 3, "grafeas.v1beta1.package.Version"
    optional :maintainer, :string, 4
    optional :url, :string, 5
    optional :description, :string, 6
  end
  add_message "grafeas.v1beta1.package.Location" do
    optional :cpe_uri, :string, 1
    optional :version, :message, 2, "grafeas.v1beta1.package.Version"
    optional :path, :string, 3
  end
  add_message "grafeas.v1beta1.package.Package" do
    optional :name, :string, 1
    repeated :distribution, :message, 10, "grafeas.v1beta1.package.Distribution"
  end
  add_message "grafeas.v1beta1.package.Details" do
    optional :installation, :message, 1, "grafeas.v1beta1.package.Installation"
  end
  add_message "grafeas.v1beta1.package.Installation" do
    optional :name, :string, 1
    repeated :location, :message, 2, "grafeas.v1beta1.package.Location"
  end
  add_message "grafeas.v1beta1.package.Version" do
    optional :epoch, :int32, 1
    optional :name, :string, 2
    optional :revision, :string, 3
    optional :kind, :enum, 4, "grafeas.v1beta1.package.Version.VersionKind"
  end
  add_enum "grafeas.v1beta1.package.Version.VersionKind" do
    value :VERSION_KIND_UNSPECIFIED, 0
    value :NORMAL, 1
    value :MINIMUM, 2
    value :MAXIMUM, 3
  end
  add_enum "grafeas.v1beta1.package.Architecture" do
    value :ARCHITECTURE_UNSPECIFIED, 0
    value :X86, 1
    value :X64, 2
  end
end

module Grafeas
  module V1beta1
    module Package
      Distribution = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.package.Distribution").msgclass
      Location = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.package.Location").msgclass
      Package = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.package.Package").msgclass
      Details = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.package.Details").msgclass
      Installation = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.package.Installation").msgclass
      Version = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.package.Version").msgclass
      Version::VersionKind = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.package.Version.VersionKind").enummodule
      Architecture = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.package.Architecture").enummodule
    end
  end
end
