<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1beta1/containeranalysis.proto

namespace Google\Devtools\Containeranalysis\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A request to update a scan configuration.
 *
 * Generated from protobuf message <code>google.devtools.containeranalysis.v1beta1.UpdateScanConfigRequest</code>
 */
class UpdateScanConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The name of the scan configuration in the form of
     * `projects/[PROJECT_ID]/scanConfigs/[SCAN_CONFIG_ID]`.
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $name = '';
    /**
     * Required. The updated scan configuration.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1beta1.ScanConfig scan_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $scan_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Required. The name of the scan configuration in the form of
     *           `projects/[PROJECT_ID]/scanConfigs/[SCAN_CONFIG_ID]`.
     *     @type \Google\Devtools\Containeranalysis\V1beta1\ScanConfig $scan_config
     *           Required. The updated scan configuration.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Containeranalysis\V1Beta1\Containeranalysis::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The name of the scan configuration in the form of
     * `projects/[PROJECT_ID]/scanConfigs/[SCAN_CONFIG_ID]`.
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Required. The name of the scan configuration in the form of
     * `projects/[PROJECT_ID]/scanConfigs/[SCAN_CONFIG_ID]`.
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Required. The updated scan configuration.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1beta1.ScanConfig scan_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Devtools\Containeranalysis\V1beta1\ScanConfig
     */
    public function getScanConfig()
    {
        return $this->scan_config;
    }

    /**
     * Required. The updated scan configuration.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1beta1.ScanConfig scan_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Google\Devtools\Containeranalysis\V1beta1\ScanConfig $var
     * @return $this
     */
    public function setScanConfig($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1beta1\ScanConfig::class);
        $this->scan_config = $var;

        return $this;
    }

}

