// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4beta1/event_service.proto

package com.google.cloud.talent.v4beta1;

public final class EventServiceProto {
  private EventServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_talent_v4beta1_CreateClientEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_talent_v4beta1_CreateClientEventRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/google/cloud/talent/v4beta1/event_serv" +
      "ice.proto\022\033google.cloud.talent.v4beta1\032\034" +
      "google/api/annotations.proto\032\027google/api" +
      "/client.proto\032\037google/api/field_behavior" +
      ".proto\032\031google/api/resource.proto\032\'googl" +
      "e/cloud/talent/v4beta1/event.proto\"\222\001\n\030C" +
      "reateClientEventRequest\0221\n\006parent\030\001 \001(\tB" +
      "!\340A\002\372A\033\022\031jobs.googleapis.com/Event\022C\n\014cl" +
      "ient_event\030\002 \001(\0132(.google.cloud.talent.v" +
      "4beta1.ClientEventB\003\340A\0022\372\002\n\014EventService" +
      "\022\373\001\n\021CreateClientEvent\0225.google.cloud.ta" +
      "lent.v4beta1.CreateClientEventRequest\032(." +
      "google.cloud.talent.v4beta1.ClientEvent\"" +
      "\204\001\202\323\344\223\002h\"3/v4beta1/{parent=projects/*/te" +
      "nants/*}/clientEvents:\001*Z.\")/v4beta1/{pa" +
      "rent=projects/*}/clientEvents:\001*\332A\023paren" +
      "t,client_event\032l\312A\023jobs.googleapis.com\322A" +
      "Shttps://www.googleapis.com/auth/cloud-p" +
      "latform,https://www.googleapis.com/auth/" +
      "jobsB\177\n\037com.google.cloud.talent.v4beta1B" +
      "\021EventServiceProtoP\001ZAgoogle.golang.org/" +
      "genproto/googleapis/cloud/talent/v4beta1" +
      ";talent\242\002\003CTSb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.cloud.talent.v4beta1.EventProto.getDescriptor(),
        });
    internal_static_google_cloud_talent_v4beta1_CreateClientEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_talent_v4beta1_CreateClientEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_talent_v4beta1_CreateClientEventRequest_descriptor,
        new java.lang.String[] { "Parent", "ClientEvent", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.talent.v4beta1.EventProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
