// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/cloud/dataproc/v1beta2/shared.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Cloud.Dataproc.V1Beta2 {

  /// <summary>Holder for reflection information generated from google/cloud/dataproc/v1beta2/shared.proto</summary>
  public static partial class SharedReflection {

    #region Descriptor
    /// <summary>File descriptor for google/cloud/dataproc/v1beta2/shared.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SharedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cipnb29nbGUvY2xvdWQvZGF0YXByb2MvdjFiZXRhMi9zaGFyZWQucHJvdG8S",
            "HWdvb2dsZS5jbG91ZC5kYXRhcHJvYy52MWJldGEyGhxnb29nbGUvYXBpL2Fu",
            "bm90YXRpb25zLnByb3RvKpUBCglDb21wb25lbnQSGQoVQ09NUE9ORU5UX1VO",
            "U1BFQ0lGSUVEEAASDAoIQU5BQ09OREEQBRIJCgVEUlVJRBAJEhAKDEhJVkVf",
            "V0VCSENBVBADEgsKB0pVUFlURVIQARIMCghLRVJCRVJPUxAHEgoKBlBSRVNU",
            "TxAGEgwKCFpFUFBFTElOEAQSDQoJWk9PS0VFUEVSEAhCeQohY29tLmdvb2ds",
            "ZS5jbG91ZC5kYXRhcHJvYy52MWJldGEyQgtTaGFyZWRQcm90b1ABWkVnb29n",
            "bGUuZ29sYW5nLm9yZy9nZW5wcm90by9nb29nbGVhcGlzL2Nsb3VkL2RhdGFw",
            "cm9jL3YxYmV0YTI7ZGF0YXByb2NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Cloud.Dataproc.V1Beta2.Component), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Cluster components that can be activated.
  /// </summary>
  public enum Component {
    /// <summary>
    /// Unspecified component.
    /// </summary>
    [pbr::OriginalName("COMPONENT_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// The Anaconda python distribution.
    /// </summary>
    [pbr::OriginalName("ANACONDA")] Anaconda = 5,
    /// <summary>
    /// The Druid query engine.
    /// </summary>
    [pbr::OriginalName("DRUID")] Druid = 9,
    /// <summary>
    /// The Hive Web HCatalog (the REST service for accessing HCatalog).
    /// </summary>
    [pbr::OriginalName("HIVE_WEBHCAT")] HiveWebhcat = 3,
    /// <summary>
    /// The Jupyter Notebook.
    /// </summary>
    [pbr::OriginalName("JUPYTER")] Jupyter = 1,
    /// <summary>
    /// The Kerberos security feature.
    /// </summary>
    [pbr::OriginalName("KERBEROS")] Kerberos = 7,
    /// <summary>
    /// The Presto query engine.
    /// </summary>
    [pbr::OriginalName("PRESTO")] Presto = 6,
    /// <summary>
    /// The Zeppelin notebook.
    /// </summary>
    [pbr::OriginalName("ZEPPELIN")] Zeppelin = 4,
    /// <summary>
    /// The Zookeeper service.
    /// </summary>
    [pbr::OriginalName("ZOOKEEPER")] Zookeeper = 8,
  }

  #endregion

}

#endregion Designer generated code
