// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/privacy/dlp/v2/dlp.proto

package com.google.privacy.dlp.v2;

public interface UpdateJobTriggerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.privacy.dlp.v2.UpdateJobTriggerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Resource name of the project and the triggeredJob, for example
   * `projects/dlp-test-project/jobTriggers/53234423`.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. Resource name of the project and the triggeredJob, for example
   * `projects/dlp-test-project/jobTriggers/53234423`.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * New JobTrigger value.
   * </pre>
   *
   * <code>.google.privacy.dlp.v2.JobTrigger job_trigger = 2;</code>
   */
  boolean hasJobTrigger();
  /**
   * <pre>
   * New JobTrigger value.
   * </pre>
   *
   * <code>.google.privacy.dlp.v2.JobTrigger job_trigger = 2;</code>
   */
  com.google.privacy.dlp.v2.JobTrigger getJobTrigger();
  /**
   * <pre>
   * New JobTrigger value.
   * </pre>
   *
   * <code>.google.privacy.dlp.v2.JobTrigger job_trigger = 2;</code>
   */
  com.google.privacy.dlp.v2.JobTriggerOrBuilder getJobTriggerOrBuilder();

  /**
   * <pre>
   * Mask to control which fields get updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 3;</code>
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * Mask to control which fields get updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 3;</code>
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * Mask to control which fields get updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 3;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
