# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1beta1/deployment/deployment.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grafeas.v1beta1.deployment.Deployable" do
    repeated :resource_uri, :string, 1
  end
  add_message "grafeas.v1beta1.deployment.Details" do
    optional :deployment, :message, 1, "grafeas.v1beta1.deployment.Deployment"
  end
  add_message "grafeas.v1beta1.deployment.Deployment" do
    optional :user_email, :string, 1
    optional :deploy_time, :message, 2, "google.protobuf.Timestamp"
    optional :undeploy_time, :message, 3, "google.protobuf.Timestamp"
    optional :config, :string, 4
    optional :address, :string, 5
    repeated :resource_uri, :string, 6
    optional :platform, :enum, 7, "grafeas.v1beta1.deployment.Deployment.Platform"
  end
  add_enum "grafeas.v1beta1.deployment.Deployment.Platform" do
    value :PLATFORM_UNSPECIFIED, 0
    value :GKE, 1
    value :FLEX, 2
    value :CUSTOM, 3
  end
end

module Grafeas
  module V1beta1
    module Deployment
      Deployable = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.deployment.Deployable").msgclass
      Details = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.deployment.Details").msgclass
      Deployment = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.deployment.Deployment").msgclass
      Deployment::Platform = Google::Protobuf::DescriptorPool.generated_pool.lookup("grafeas.v1beta1.deployment.Deployment.Platform").enummodule
    end
  end
end
