# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1alpha1/image_basis.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.devtools.containeranalysis.v1alpha1.DockerImage" do
  end
  add_message "google.devtools.containeranalysis.v1alpha1.DockerImage.Layer" do
    optional :directive, :enum, 1, "google.devtools.containeranalysis.v1alpha1.DockerImage.Layer.Directive"
    optional :arguments, :string, 2
  end
  add_enum "google.devtools.containeranalysis.v1alpha1.DockerImage.Layer.Directive" do
    value :DIRECTIVE_UNSPECIFIED, 0
    value :MAINTAINER, 1
    value :RUN, 2
    value :CMD, 3
    value :LABEL, 4
    value :EXPOSE, 5
    value :ENV, 6
    value :ADD, 7
    value :COPY, 8
    value :ENTRYPOINT, 9
    value :VOLUME, 10
    value :USER, 11
    value :WORKDIR, 12
    value :ARG, 13
    value :ONBUILD, 14
    value :STOPSIGNAL, 15
    value :HEALTHCHECK, 16
    value :SHELL, 17
  end
  add_message "google.devtools.containeranalysis.v1alpha1.DockerImage.Fingerprint" do
    optional :v1_name, :string, 1
    repeated :v2_blob, :string, 2
    optional :v2_name, :string, 3
  end
  add_message "google.devtools.containeranalysis.v1alpha1.DockerImage.Basis" do
    optional :resource_url, :string, 1
    optional :fingerprint, :message, 2, "google.devtools.containeranalysis.v1alpha1.DockerImage.Fingerprint"
  end
  add_message "google.devtools.containeranalysis.v1alpha1.DockerImage.Derived" do
    optional :fingerprint, :message, 1, "google.devtools.containeranalysis.v1alpha1.DockerImage.Fingerprint"
    optional :distance, :uint32, 2
    repeated :layer_info, :message, 3, "google.devtools.containeranalysis.v1alpha1.DockerImage.Layer"
    optional :base_resource_url, :string, 4
  end
end

module Google
  module Devtools
    module Containeranalysis
      module V1alpha1
        DockerImage = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.DockerImage").msgclass
        DockerImage::Layer = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.DockerImage.Layer").msgclass
        DockerImage::Layer::Directive = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.DockerImage.Layer.Directive").enummodule
        DockerImage::Fingerprint = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.DockerImage.Fingerprint").msgclass
        DockerImage::Basis = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.DockerImage.Basis").msgclass
        DockerImage::Derived = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.DockerImage.Derived").msgclass
      end
    end
  end
end
