# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1alpha1/provenance.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/devtools/containeranalysis/v1alpha1/source_context_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.devtools.containeranalysis.v1alpha1.BuildProvenance" do
    optional :id, :string, 1
    optional :project_id, :string, 2
    repeated :commands, :message, 5, "google.devtools.containeranalysis.v1alpha1.Command"
    repeated :built_artifacts, :message, 6, "google.devtools.containeranalysis.v1alpha1.Artifact"
    optional :create_time, :message, 7, "google.protobuf.Timestamp"
    optional :start_time, :message, 8, "google.protobuf.Timestamp"
    optional :finish_time, :message, 9, "google.protobuf.Timestamp"
    optional :creator, :string, 11
    optional :logs_bucket, :string, 13
    optional :source_provenance, :message, 14, "google.devtools.containeranalysis.v1alpha1.Source"
    optional :trigger_id, :string, 15
    map :build_options, :string, :string, 16
    optional :builder_version, :string, 17
  end
  add_message "google.devtools.containeranalysis.v1alpha1.Source" do
    optional :artifact_storage_source, :message, 4, "google.devtools.containeranalysis.v1alpha1.StorageSource"
    map :file_hashes, :string, :message, 3, "google.devtools.containeranalysis.v1alpha1.FileHashes"
    optional :context, :message, 7, "google.devtools.containeranalysis.v1alpha1.SourceContext"
    repeated :additional_contexts, :message, 8, "google.devtools.containeranalysis.v1alpha1.SourceContext"
    oneof :source do
      optional :storage_source, :message, 1, "google.devtools.containeranalysis.v1alpha1.StorageSource"
      optional :repo_source, :message, 2, "google.devtools.containeranalysis.v1alpha1.RepoSource"
    end
  end
  add_message "google.devtools.containeranalysis.v1alpha1.FileHashes" do
    repeated :file_hash, :message, 1, "google.devtools.containeranalysis.v1alpha1.Hash"
  end
  add_message "google.devtools.containeranalysis.v1alpha1.Hash" do
    optional :type, :enum, 1, "google.devtools.containeranalysis.v1alpha1.Hash.HashType"
    optional :value, :bytes, 2
  end
  add_enum "google.devtools.containeranalysis.v1alpha1.Hash.HashType" do
    value :NONE, 0
    value :SHA256, 1
  end
  add_message "google.devtools.containeranalysis.v1alpha1.StorageSource" do
    optional :bucket, :string, 1
    optional :object, :string, 2
    optional :generation, :int64, 3
  end
  add_message "google.devtools.containeranalysis.v1alpha1.RepoSource" do
    optional :project_id, :string, 1
    optional :repo_name, :string, 2
    oneof :revision do
      optional :branch_name, :string, 3
      optional :tag_name, :string, 4
      optional :commit_sha, :string, 5
    end
  end
  add_message "google.devtools.containeranalysis.v1alpha1.Command" do
    optional :name, :string, 1
    repeated :env, :string, 2
    repeated :args, :string, 3
    optional :dir, :string, 4
    optional :id, :string, 5
    repeated :wait_for, :string, 6
  end
  add_message "google.devtools.containeranalysis.v1alpha1.Artifact" do
    optional :name, :string, 1
    optional :checksum, :string, 2
    optional :id, :string, 3
    repeated :names, :string, 4
  end
end

module Google
  module Devtools
    module Containeranalysis
      module V1alpha1
        BuildProvenance = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.BuildProvenance").msgclass
        Source = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.Source").msgclass
        FileHashes = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.FileHashes").msgclass
        Hash = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.Hash").msgclass
        Hash::HashType = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.Hash.HashType").enummodule
        StorageSource = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.StorageSource").msgclass
        RepoSource = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.RepoSource").msgclass
        Command = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.Command").msgclass
        Artifact = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.containeranalysis.v1alpha1.Artifact").msgclass
      end
    end
  end
end
