// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/devtools/containeranalysis/v1beta1/image/image.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grafeas.V1Beta1.Image {

  /// <summary>Holder for reflection information generated from google/devtools/containeranalysis/v1beta1/image/image.proto</summary>
  public static partial class ImageReflection {

    #region Descriptor
    /// <summary>File descriptor for google/devtools/containeranalysis/v1beta1/image/image.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ImageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjtnb29nbGUvZGV2dG9vbHMvY29udGFpbmVyYW5hbHlzaXMvdjFiZXRhMS9p",
            "bWFnZS9pbWFnZS5wcm90bxIVZ3JhZmVhcy52MWJldGExLmltYWdlIsgCCgVM",
            "YXllchI5CglkaXJlY3RpdmUYASABKA4yJi5ncmFmZWFzLnYxYmV0YTEuaW1h",
            "Z2UuTGF5ZXIuRGlyZWN0aXZlEhEKCWFyZ3VtZW50cxgCIAEoCSLwAQoJRGly",
            "ZWN0aXZlEhkKFURJUkVDVElWRV9VTlNQRUNJRklFRBAAEg4KCk1BSU5UQUlO",
            "RVIQARIHCgNSVU4QAhIHCgNDTUQQAxIJCgVMQUJFTBAEEgoKBkVYUE9TRRAF",
            "EgcKA0VOVhAGEgcKA0FERBAHEggKBENPUFkQCBIOCgpFTlRSWVBPSU5UEAkS",
            "CgoGVk9MVU1FEAoSCAoEVVNFUhALEgsKB1dPUktESVIQDBIHCgNBUkcQDRIL",
            "CgdPTkJVSUxEEA4SDgoKU1RPUFNJR05BTBAPEg8KC0hFQUxUSENIRUNLEBAS",
            "CQoFU0hFTEwQESJACgtGaW5nZXJwcmludBIPCgd2MV9uYW1lGAEgASgJEg8K",
            "B3YyX2Jsb2IYAiADKAkSDwoHdjJfbmFtZRgDIAEoCSJWCgVCYXNpcxIUCgxy",
            "ZXNvdXJjZV91cmwYASABKAkSNwoLZmluZ2VycHJpbnQYAiABKAsyIi5ncmFm",
            "ZWFzLnYxYmV0YTEuaW1hZ2UuRmluZ2VycHJpbnQiQAoHRGV0YWlscxI1Cg1k",
            "ZXJpdmVkX2ltYWdlGAEgASgLMh4uZ3JhZmVhcy52MWJldGExLmltYWdlLkRl",
            "cml2ZWQioQEKB0Rlcml2ZWQSNwoLZmluZ2VycHJpbnQYASABKAsyIi5ncmFm",
            "ZWFzLnYxYmV0YTEuaW1hZ2UuRmluZ2VycHJpbnQSEAoIZGlzdGFuY2UYAiAB",
            "KAUSMAoKbGF5ZXJfaW5mbxgDIAMoCzIcLmdyYWZlYXMudjFiZXRhMS5pbWFn",
            "ZS5MYXllchIZChFiYXNlX3Jlc291cmNlX3VybBgEIAEoCUJ4Chhpby5ncmFm",
            "ZWFzLnYxYmV0YTEuaW1hZ2VQAVpUZ29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJv",
            "dG8vZ29vZ2xlYXBpcy9kZXZ0b29scy9jb250YWluZXJhbmFseXNpcy92MWJl",
            "dGExL2ltYWdlO2ltYWdlogIDR1JBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Grafeas.V1Beta1.Image.Layer), global::Grafeas.V1Beta1.Image.Layer.Parser, new[]{ "Directive", "Arguments" }, null, new[]{ typeof(global::Grafeas.V1Beta1.Image.Layer.Types.Directive) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grafeas.V1Beta1.Image.Fingerprint), global::Grafeas.V1Beta1.Image.Fingerprint.Parser, new[]{ "V1Name", "V2Blob", "V2Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grafeas.V1Beta1.Image.Basis), global::Grafeas.V1Beta1.Image.Basis.Parser, new[]{ "ResourceUrl", "Fingerprint" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grafeas.V1Beta1.Image.Details), global::Grafeas.V1Beta1.Image.Details.Parser, new[]{ "DerivedImage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grafeas.V1Beta1.Image.Derived), global::Grafeas.V1Beta1.Image.Derived.Parser, new[]{ "Fingerprint", "Distance", "LayerInfo", "BaseResourceUrl" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Layer holds metadata specific to a layer of a Docker image.
  /// </summary>
  public sealed partial class Layer : pb::IMessage<Layer> {
    private static readonly pb::MessageParser<Layer> _parser = new pb::MessageParser<Layer>(() => new Layer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Layer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grafeas.V1Beta1.Image.ImageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Layer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Layer(Layer other) : this() {
      directive_ = other.directive_;
      arguments_ = other.arguments_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Layer Clone() {
      return new Layer(this);
    }

    /// <summary>Field number for the "directive" field.</summary>
    public const int DirectiveFieldNumber = 1;
    private global::Grafeas.V1Beta1.Image.Layer.Types.Directive directive_ = global::Grafeas.V1Beta1.Image.Layer.Types.Directive.Unspecified;
    /// <summary>
    /// Required. The recovered Dockerfile directive used to construct this layer.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grafeas.V1Beta1.Image.Layer.Types.Directive Directive {
      get { return directive_; }
      set {
        directive_ = value;
      }
    }

    /// <summary>Field number for the "arguments" field.</summary>
    public const int ArgumentsFieldNumber = 2;
    private string arguments_ = "";
    /// <summary>
    /// The recovered arguments to the Dockerfile directive.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Arguments {
      get { return arguments_; }
      set {
        arguments_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Layer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Layer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Directive != other.Directive) return false;
      if (Arguments != other.Arguments) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Directive != global::Grafeas.V1Beta1.Image.Layer.Types.Directive.Unspecified) hash ^= Directive.GetHashCode();
      if (Arguments.Length != 0) hash ^= Arguments.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Directive != global::Grafeas.V1Beta1.Image.Layer.Types.Directive.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Directive);
      }
      if (Arguments.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Arguments);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Directive != global::Grafeas.V1Beta1.Image.Layer.Types.Directive.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Directive);
      }
      if (Arguments.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Arguments);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Layer other) {
      if (other == null) {
        return;
      }
      if (other.Directive != global::Grafeas.V1Beta1.Image.Layer.Types.Directive.Unspecified) {
        Directive = other.Directive;
      }
      if (other.Arguments.Length != 0) {
        Arguments = other.Arguments;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Directive = (global::Grafeas.V1Beta1.Image.Layer.Types.Directive) input.ReadEnum();
            break;
          }
          case 18: {
            Arguments = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Layer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Instructions from Dockerfile.
      /// </summary>
      public enum Directive {
        /// <summary>
        /// Default value for unsupported/missing directive.
        /// </summary>
        [pbr::OriginalName("DIRECTIVE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("MAINTAINER")] Maintainer = 1,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("RUN")] Run = 2,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("CMD")] Cmd = 3,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("LABEL")] Label = 4,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("EXPOSE")] Expose = 5,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("ENV")] Env = 6,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("ADD")] Add = 7,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("COPY")] Copy = 8,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("ENTRYPOINT")] Entrypoint = 9,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("VOLUME")] Volume = 10,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("USER")] User = 11,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("WORKDIR")] Workdir = 12,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("ARG")] Arg = 13,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("ONBUILD")] Onbuild = 14,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("STOPSIGNAL")] Stopsignal = 15,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("HEALTHCHECK")] Healthcheck = 16,
        /// <summary>
        /// https://docs.docker.com/engine/reference/builder/
        /// </summary>
        [pbr::OriginalName("SHELL")] Shell = 17,
      }

    }
    #endregion

  }

  /// <summary>
  /// A set of properties that uniquely identify a given Docker image.
  /// </summary>
  public sealed partial class Fingerprint : pb::IMessage<Fingerprint> {
    private static readonly pb::MessageParser<Fingerprint> _parser = new pb::MessageParser<Fingerprint>(() => new Fingerprint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Fingerprint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grafeas.V1Beta1.Image.ImageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Fingerprint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Fingerprint(Fingerprint other) : this() {
      v1Name_ = other.v1Name_;
      v2Blob_ = other.v2Blob_.Clone();
      v2Name_ = other.v2Name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Fingerprint Clone() {
      return new Fingerprint(this);
    }

    /// <summary>Field number for the "v1_name" field.</summary>
    public const int V1NameFieldNumber = 1;
    private string v1Name_ = "";
    /// <summary>
    /// Required. The layer ID of the final layer in the Docker image's v1
    /// representation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string V1Name {
      get { return v1Name_; }
      set {
        v1Name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "v2_blob" field.</summary>
    public const int V2BlobFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_v2Blob_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> v2Blob_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Required. The ordered list of v2 blobs that represent a given image.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> V2Blob {
      get { return v2Blob_; }
    }

    /// <summary>Field number for the "v2_name" field.</summary>
    public const int V2NameFieldNumber = 3;
    private string v2Name_ = "";
    /// <summary>
    /// Output only. The name of the image's v2 blobs computed via:
    ///   [bottom] := v2_blob[bottom]
    ///   [N] := sha256(v2_blob[N] + " " + v2_name[N+1])
    /// Only the name of the final blob is kept.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string V2Name {
      get { return v2Name_; }
      set {
        v2Name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Fingerprint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Fingerprint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (V1Name != other.V1Name) return false;
      if(!v2Blob_.Equals(other.v2Blob_)) return false;
      if (V2Name != other.V2Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (V1Name.Length != 0) hash ^= V1Name.GetHashCode();
      hash ^= v2Blob_.GetHashCode();
      if (V2Name.Length != 0) hash ^= V2Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (V1Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(V1Name);
      }
      v2Blob_.WriteTo(output, _repeated_v2Blob_codec);
      if (V2Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(V2Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (V1Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(V1Name);
      }
      size += v2Blob_.CalculateSize(_repeated_v2Blob_codec);
      if (V2Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(V2Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Fingerprint other) {
      if (other == null) {
        return;
      }
      if (other.V1Name.Length != 0) {
        V1Name = other.V1Name;
      }
      v2Blob_.Add(other.v2Blob_);
      if (other.V2Name.Length != 0) {
        V2Name = other.V2Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            V1Name = input.ReadString();
            break;
          }
          case 18: {
            v2Blob_.AddEntriesFrom(input, _repeated_v2Blob_codec);
            break;
          }
          case 26: {
            V2Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Basis describes the base image portion (Note) of the DockerImage
  /// relationship. Linked occurrences are derived from this or an
  /// equivalent image via:
  ///   FROM &lt;Basis.resource_url>
  /// Or an equivalent reference, e.g. a tag of the resource_url.
  /// </summary>
  public sealed partial class Basis : pb::IMessage<Basis> {
    private static readonly pb::MessageParser<Basis> _parser = new pb::MessageParser<Basis>(() => new Basis());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Basis> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grafeas.V1Beta1.Image.ImageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Basis() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Basis(Basis other) : this() {
      resourceUrl_ = other.resourceUrl_;
      fingerprint_ = other.fingerprint_ != null ? other.fingerprint_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Basis Clone() {
      return new Basis(this);
    }

    /// <summary>Field number for the "resource_url" field.</summary>
    public const int ResourceUrlFieldNumber = 1;
    private string resourceUrl_ = "";
    /// <summary>
    /// Required. Immutable. The resource_url for the resource representing the
    /// basis of associated occurrence images.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResourceUrl {
      get { return resourceUrl_; }
      set {
        resourceUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fingerprint" field.</summary>
    public const int FingerprintFieldNumber = 2;
    private global::Grafeas.V1Beta1.Image.Fingerprint fingerprint_;
    /// <summary>
    /// Required. Immutable. The fingerprint of the base image.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grafeas.V1Beta1.Image.Fingerprint Fingerprint {
      get { return fingerprint_; }
      set {
        fingerprint_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Basis);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Basis other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResourceUrl != other.ResourceUrl) return false;
      if (!object.Equals(Fingerprint, other.Fingerprint)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResourceUrl.Length != 0) hash ^= ResourceUrl.GetHashCode();
      if (fingerprint_ != null) hash ^= Fingerprint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResourceUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceUrl);
      }
      if (fingerprint_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Fingerprint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResourceUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceUrl);
      }
      if (fingerprint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Fingerprint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Basis other) {
      if (other == null) {
        return;
      }
      if (other.ResourceUrl.Length != 0) {
        ResourceUrl = other.ResourceUrl;
      }
      if (other.fingerprint_ != null) {
        if (fingerprint_ == null) {
          Fingerprint = new global::Grafeas.V1Beta1.Image.Fingerprint();
        }
        Fingerprint.MergeFrom(other.Fingerprint);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResourceUrl = input.ReadString();
            break;
          }
          case 18: {
            if (fingerprint_ == null) {
              Fingerprint = new global::Grafeas.V1Beta1.Image.Fingerprint();
            }
            input.ReadMessage(Fingerprint);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Details of an image occurrence.
  /// </summary>
  public sealed partial class Details : pb::IMessage<Details> {
    private static readonly pb::MessageParser<Details> _parser = new pb::MessageParser<Details>(() => new Details());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Details> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grafeas.V1Beta1.Image.ImageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Details() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Details(Details other) : this() {
      derivedImage_ = other.derivedImage_ != null ? other.derivedImage_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Details Clone() {
      return new Details(this);
    }

    /// <summary>Field number for the "derived_image" field.</summary>
    public const int DerivedImageFieldNumber = 1;
    private global::Grafeas.V1Beta1.Image.Derived derivedImage_;
    /// <summary>
    /// Required. Immutable. The child image derived from the base image.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grafeas.V1Beta1.Image.Derived DerivedImage {
      get { return derivedImage_; }
      set {
        derivedImage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Details);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Details other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(DerivedImage, other.DerivedImage)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (derivedImage_ != null) hash ^= DerivedImage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (derivedImage_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DerivedImage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (derivedImage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DerivedImage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Details other) {
      if (other == null) {
        return;
      }
      if (other.derivedImage_ != null) {
        if (derivedImage_ == null) {
          DerivedImage = new global::Grafeas.V1Beta1.Image.Derived();
        }
        DerivedImage.MergeFrom(other.DerivedImage);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (derivedImage_ == null) {
              DerivedImage = new global::Grafeas.V1Beta1.Image.Derived();
            }
            input.ReadMessage(DerivedImage);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Derived describes the derived image portion (Occurrence) of the DockerImage
  /// relationship. This image would be produced from a Dockerfile with FROM
  /// &lt;DockerImage.Basis in attached Note>.
  /// </summary>
  public sealed partial class Derived : pb::IMessage<Derived> {
    private static readonly pb::MessageParser<Derived> _parser = new pb::MessageParser<Derived>(() => new Derived());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Derived> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grafeas.V1Beta1.Image.ImageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Derived() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Derived(Derived other) : this() {
      fingerprint_ = other.fingerprint_ != null ? other.fingerprint_.Clone() : null;
      distance_ = other.distance_;
      layerInfo_ = other.layerInfo_.Clone();
      baseResourceUrl_ = other.baseResourceUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Derived Clone() {
      return new Derived(this);
    }

    /// <summary>Field number for the "fingerprint" field.</summary>
    public const int FingerprintFieldNumber = 1;
    private global::Grafeas.V1Beta1.Image.Fingerprint fingerprint_;
    /// <summary>
    /// Required. The fingerprint of the derived image.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grafeas.V1Beta1.Image.Fingerprint Fingerprint {
      get { return fingerprint_; }
      set {
        fingerprint_ = value;
      }
    }

    /// <summary>Field number for the "distance" field.</summary>
    public const int DistanceFieldNumber = 2;
    private int distance_;
    /// <summary>
    /// Output only. The number of layers by which this image differs from the
    /// associated image basis.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    /// <summary>Field number for the "layer_info" field.</summary>
    public const int LayerInfoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Grafeas.V1Beta1.Image.Layer> _repeated_layerInfo_codec
        = pb::FieldCodec.ForMessage(26, global::Grafeas.V1Beta1.Image.Layer.Parser);
    private readonly pbc::RepeatedField<global::Grafeas.V1Beta1.Image.Layer> layerInfo_ = new pbc::RepeatedField<global::Grafeas.V1Beta1.Image.Layer>();
    /// <summary>
    /// This contains layer-specific metadata, if populated it has length
    /// "distance" and is ordered with [distance] being the layer immediately
    /// following the base image and [1] being the final layer.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grafeas.V1Beta1.Image.Layer> LayerInfo {
      get { return layerInfo_; }
    }

    /// <summary>Field number for the "base_resource_url" field.</summary>
    public const int BaseResourceUrlFieldNumber = 4;
    private string baseResourceUrl_ = "";
    /// <summary>
    /// Output only. This contains the base image URL for the derived image
    /// occurrence.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BaseResourceUrl {
      get { return baseResourceUrl_; }
      set {
        baseResourceUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Derived);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Derived other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Fingerprint, other.Fingerprint)) return false;
      if (Distance != other.Distance) return false;
      if(!layerInfo_.Equals(other.layerInfo_)) return false;
      if (BaseResourceUrl != other.BaseResourceUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (fingerprint_ != null) hash ^= Fingerprint.GetHashCode();
      if (Distance != 0) hash ^= Distance.GetHashCode();
      hash ^= layerInfo_.GetHashCode();
      if (BaseResourceUrl.Length != 0) hash ^= BaseResourceUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (fingerprint_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Fingerprint);
      }
      if (Distance != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Distance);
      }
      layerInfo_.WriteTo(output, _repeated_layerInfo_codec);
      if (BaseResourceUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(BaseResourceUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (fingerprint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Fingerprint);
      }
      if (Distance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Distance);
      }
      size += layerInfo_.CalculateSize(_repeated_layerInfo_codec);
      if (BaseResourceUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BaseResourceUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Derived other) {
      if (other == null) {
        return;
      }
      if (other.fingerprint_ != null) {
        if (fingerprint_ == null) {
          Fingerprint = new global::Grafeas.V1Beta1.Image.Fingerprint();
        }
        Fingerprint.MergeFrom(other.Fingerprint);
      }
      if (other.Distance != 0) {
        Distance = other.Distance;
      }
      layerInfo_.Add(other.layerInfo_);
      if (other.BaseResourceUrl.Length != 0) {
        BaseResourceUrl = other.BaseResourceUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (fingerprint_ == null) {
              Fingerprint = new global::Grafeas.V1Beta1.Image.Fingerprint();
            }
            input.ReadMessage(Fingerprint);
            break;
          }
          case 16: {
            Distance = input.ReadInt32();
            break;
          }
          case 26: {
            layerInfo_.AddEntriesFrom(input, _repeated_layerInfo_codec);
            break;
          }
          case 34: {
            BaseResourceUrl = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
